pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete-1') {
            steps {
                echo 'Job Complete-1!'
            }
        }
                stage('Complete-2') {
            steps {
                echo 'Job Complete-2!'
            }
        }
                        stage('Complete-3') {
            steps {
                echo 'Job Complete-3!'
            }
        }
                        stage('Complete-4') {
            steps {
                echo 'Job Complete-4!'
            }
        }
                                stage('Complete-5') {
            steps {
                echo 'Job Complete-5!'
            }
        }
        
    }
}
